name: kinfraglib
channels:
  - conda-forge
dependencies:
  # Base dependencies
  - python
  - pip
  # Package dependencies
  - biopandas
  - chembl_webresource_client
  - ijson
  - ipywidgets>=7.5
  - jupyterlab
  - matplotlib
  - numpy
  - pandas=1.1.2
  - rdkit=2020.03.3
  - scikit-learn
  - seaborn
  - lich::syba
  - redo
  ## CI tests
  # Workaround for https://github.com/computationalmodelling/nbval/issues/153
  - pytest 5.*
  - pytest-xdist
  - nbval
  - shyaml  
  # Remove when opencadd is conda-installable
  - biopython 1.77
  - bravado
  - nglview
  - scipy
  - tqdm
  - pip:
    - black-nb
    - https://github.com/volkamerlab/opencadd/archive/2a6cf9bcee72a3626114cda82af758e05ed5af18.zip
    # KinFragLib itself
    - https://github.com/volkamerlab/kinfraglib/archive/master.tar.gz
