name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      - "custom-base"
  schedule:
    # Run a cron job once daily, weekdays only
    - cron: "0 3 1,15 * *"

jobs:
  test:
    name: Pytest
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: ubuntu-latest
            python-version: "3.6"
          - os: ubuntu-latest
            python-version: "3.8"
          #- os: ubuntu-latest
          #  python-version: "3.9"
          #- os: macos-latest
          #  python-version: "3.6"
          #- os: windows-latest
          #  python-version: "3.6"

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.cfg.python-version }}
          activate-environment: kinfraglib
          channel-priority: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Run tests
        shell: bash -l {0}
        run: |
          # Install kinfraglib again (comes already with the environment) to ensure this commit's kinfraglib version for CI testing
          cd ..
          pip install -e KinFragLib
          cd KinFragLib
          # Run tests
          PYTEST_ARGS="--nbval-lax --current-env --nbval-cell-timeout=900"
          pytest $PYTEST_ARGS notebooks/custom_kinfraglib/

